### ISSUE TITLE
How Long To Beat section frequently shows 'No Data Found@

### ISSUE THREAD

**Issue by AndySav92** [IsThereAnyDeal/AugmentedSteam#924] opened 2020-07-02 22:27 UTC
This issue occurs for most games I view, but not all. Seems to be more common on more recent releases (within the last year or so)

![chrome_EVcSkXqKVd](https://user-images.githubusercontent.com/11989790/86414239-4756d280-bcbb-11ea-80db-8055172d45c3.png)

**Comment by seeeeew** [comment] 2020-10-06 16:24
To me it seems like this is happening only to newer games, so I assume the mappings between steam and hltb IDs aren't up to date. The comment `FIXME this is not updated from anywhere` [in the server-side code](https://github.com/tfedor/AugmentedSteam_Server/blob/5db77e776c3230e4160873582e9079780c284d74/api/storepagedata.v01.php#L339) suggests the same. Were did these mappings originally come from?

**Comment by MattHorn25** [comment] 2020-11-29 12:39
Yeah this is a very easily reproducible issue. Example game that works:
https://store.steampowered.com/app/417880/Everybodys_Gone_to_the_Rapture/
Example game that doesn't work:
https://store.steampowered.com/app/782330/DOOM_Eternal/

It looks like maybe there's a fixed server-side list matching a Steam ID to an HLTB ID for any given game, and nobody got around to figuring out a way to make it dynamic?

**Comment by Eiion** [comment] 2020-12-25 07:46
I just ran into the same issue for https://store.steampowered.com/app/578650/The_Outer_Worlds/

It's sad to see how half a year after this issue was posted there's still no fix.

**Comment by dubesor** [comment] 2021-06-19 22:30
Having the same issue, no matter what game I checked, it always shows "No data found" in How Long to Beat section. Enabled "Show HowLongToBeat.com information" in Options. Reinstalled the extension, same issue. Reproduced on Chrome and Firefox (fresh profile with default settings). Does not seem related to game age or popularity. Indie games with only a few dozen reviews have no information same as AAA titles with millions of players. When opening howlongtobeat website manually I can always see the how long to beat times, so the entries are there. Examples pages where it doesn't work (along with everywhere else for me):

https://store.steampowered.com/app/1091500/Cyberpunk_2077/
https://store.steampowered.com/app/413150/Stardew_Valley/
https://store.steampowered.com/app/8870/BioShock_Infinite/
https://store.steampowered.com/app/400/Portal/

Is this feature just completely abandoned? If so it should be removed from the options menu too.
![AShltb](https://user-images.githubusercontent.com/33842233/122656854-a593f400-d15e-11eb-8876-c91ee6347956.png)

**Comment by Revadike** [comment] 2021-06-19 22:43
If HLTB had native API support, this could be easily added without having to wait for ITAD server to implement it.

**Comment by John-Gee** [comment] 2021-11-17 18:53
Is the empty section supposed to be even visible? I can't see anything related to HLTB on any game page anymore, not even in incognito (in case another extension was blocking it). People here see the section but empty, I don't even see it.

**Comment by MattHorn25** [comment] 2021-11-22 23:58
> Is the empty section supposed to be even visible? I can't see anything related to HLTB on any game page anymore, not even in incognito (in case another extension was blocking it). People here see the section but empty, I don't even see it.

No, the empty section is no longer supposed to be visible. They merged https://github.com/IsThereAnyDeal/AugmentedSteam/pull/1185 ("Don't show HTLB section if there's no data") in June, so on most or all game pages the frame won't be visible at all until there's a way to integrate HLTB again or an alternative database is used.

**Comment by John-Gee** [comment] 2021-11-23 00:03
Thanks for the explanation Matt, you saved me time trying again for nothing! :)

**Comment by dcchambers** [comment] 2021-12-06 21:00
>Is this feature just completely abandoned? If so it should be removed from the options menu too.

👍 probably best to at least hide this from the options until it's working again.

**Comment by manuelgrabowski** [comment] 2021-12-06 21:24
> > Is this feature just completely abandoned? If so it should be removed from the options menu too.
> 
> 👍 probably best to at least hide this from the options until it's working again.

I'll have to agree with that, it was *very* confusing for me when setting up the extension a week ago. Ony when I finally found this issue after a while of trial and error, browsing the docs and googling did I understand what was going on. User experience would be much better if it was not available at all.

**Comment by dubesor** [comment] 2022-03-22 17:55
Feature seems to work again, at least on all the example links I had given 9 months ago. v2.3.1

**Comment by dcchambers** [comment] 2022-03-28 15:50
Can confirm what @dubesor wrote. While I don't see anythingin the release notes, the issue seems to be fixed. I think this can be closed.

**Comment by AndySav92** [comment] 2022-03-28 17:13
Can confirm that the issue appears to be fixed so will mark as closed

**Closed** 2022-03-28 17:12 UTC
Labels: bug

**Comment by MxtOUT** [comment] 2022-04-02 14:43
> Can confirm what @dubesor wrote. While I don't see anythingin the release notes, the issue seems to be fixed. I think this can be closed.

Yes, it was a server side fix, so it didn't require an extension update
