### ISSUE TITLE
[BUG] wrong custom links on app page

### ISSUE THREAD

**Issue by Fan4eGGG** [IsThereAnyDeal/AugmentedSteam#2078] opened 2024-11-14 23:46 UTC
I added my own link to search for the game on keymailer site. it looks like this: `https://www.keymailer.co/g/games?search%5Bavailability%5D=&amp;search%5Bq%5D=[NAME]`.
but for some reason on the game page, when you click on my hyperlink, in the link itself appears an extra request in the form of "**`amp;`**" and now it looks like this: `www.keymailer.co/g/games?search%5Bavailability%5D=&amp;search%5Bq%5D=`.

i don't know how to fix it, because i don't understand anything about it. can you help me? thank you?
thanks.

### Specifications

  - Augmented Steam Version: latest
  - Browser Version: opera one latest

**Comment by cleslie577** [comment] 2024-11-15 17:29
I came to make the same exact post having to do with Keymailer.  This wasn't an issue before, but the plugin is turning the & sign into &amp in the URL now.

**Comment by Fan4eGGG** [comment] 2024-11-15 19:25
> I came to make the same exact post having to do with Keymailer. This wasn't an issue before, but the plugin is turning the & sign into &amp in the URL now.

so we`ll wait to hear back from the dev i guess

**Comment by candela97** [comment] 2024-11-19 17:39
Duplicate of #2061

**Closed by candela97** 2024-11-19 17:39 UTC
Labels: bug

**Comment by Fan4eGGG** [comment] 2024-11-19 23:13
> Duplicate of #2061

soo, how can i fix my problem?

**Comment by candela97** [comment] 2024-11-21 14:54
The linked PR in that issue fixes this, and will be in the next release

**Comment by bxko** [comment] 2024-12-03 21:15
> > Duplicate of #2061
> 
> soo, how can i fix my problem?

If you're still looking for a fix you can use this custom TamperMonkey script I had ChatGPT make.  Just copy paste the following code:

`// ==UserScript==
// @name         Fix Keymailer Links on Steam
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  Removes "amp;" from Keymailer links on Steam pages.
// @author       Your Name
// @match        https://store.steampowered.com/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    // Monitor for clicks on the document
    document.addEventListener('click', function(event) {
        const target = event.target;

        // Check if the clicked element is a link or contains a link
        const link = target.closest('a');
        if (link) {
            // Check if the link contains "keymailer.co" and fix it if necessary
            if (link.href.includes('keymailer.co')) {
                link.href = link.href.replace(/&amp;/g, '&');
            }
        }
    }, true);
})();
`

How It Works:
URL Match: The script is set to only run on pages under the https://store.steampowered.com/* domain.
Click Event Listener: It listens for clicks on the page.
URL Correction: If a clicked link is found to contain "keymailer.co" and includes &amp;, it replaces &amp; with & in the href attribute of the link.
