### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by markwr** [IsThereAnyDeal/AugmentedSteam#1747] opened 2023-09-13 02:33 UTC
### Expected Behavior
At any store.steampowered.com page for any game, I should have a button to add/edit my notes, and I should see my notes for that game when I next load it's page..

### Actual Behavior
At store.steampowered.com pages, I no longer see my existing notes, nor is there a button to add/edit notes.

### Steps to Reproduce the Problem

  1. Go to any store.steampowered.com page for any game, and see there are no notes nor the ability to create or edit notes.
  2. 
  3. 

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Firefox 117.0.1 (32-bit)

**Comment by MxtOUT** [comment] 2023-09-13 06:23
Duplicate of #1748

**Closed by MxtOUT** 2023-09-13 06:23 UTC
Labels: bug, duplicate
