### ISSUE TITLE
[BUG] Lowest price can't display correctly in CNY

### ISSUE THREAD

**Issue by xitieshiz2** [IsThereAnyDeal/AugmentedSteam#1442] opened 2022-06-24 18:26 UTC
### Expected Behavior
Lowest price in CNY is showed on the APP page when the currency type set to CNY

### Actual Behavior
Lowest price in USD is showed on the APP page when the currency type set to CNY

### Steps to Reproduce the Problem

  1. Set currency type to CNY
  2. Navigate to any APP page
  3. See the price bar

### Specifications

  - Augmented Steam Version: 2.3.2
  - Browser Version: Microsoft Edge 102.0.1245.44
![image](https://user-images.githubusercontent.com/75575551/175641403-bfce165b-6ed9-42cf-bb62-a435060f3498.png)
![image](https://user-images.githubusercontent.com/75575551/175641721-813e6e77-cd55-49c0-b219-9da308bc241a.png)
![image](https://user-images.githubusercontent.com/75575551/175642223-3febec91-10d9-4fa6-9765-69394082c7d0.png)
![image](https://user-images.githubusercontent.com/75575551/175642488-be5d56d0-f6cf-4c5c-883c-0c3c21f86b56.png)

**Comment by candela97** [comment] 2022-06-27 14:15
It's looks normal for me when I switch to CN region when logged out:
![123123](https://user-images.githubusercontent.com/54083835/175961971-6f8c253a-d805-410f-b7ea-d27e663bf6af.jpg)

Is your store country not in CN? Since I believe Nuuvem is not available outside South America.

**Comment by xitieshiz2** [comment] 2022-06-28 22:45
> It's looks normal for me when I switch to CN region when logged out: ![123123](https://user-images.githubusercontent.com/54083835/175961971-6f8c253a-d805-410f-b7ea-d27e663bf6af.jpg)
> 
> Is your store country not in CN? Since I believe Nuuvem is not available outside South America.

I tried to remove other extensions, and the price shows correctly when I removed SteamDB extension ,that could be a compatibility issue.
But the lowest price still can not show correctly with a bundle, the problem still exists
![image](https://user-images.githubusercontent.com/75575551/176316641-d125972f-3217-4af6-86b2-c95ab38b7191.png)
![image](https://user-images.githubusercontent.com/75575551/176316671-ccff9d54-9621-4712-bcda-110fdee798cb.png)
And, yes, I'm sure that this account is in CN region

**Comment by candela97** [comment] 2022-06-29 08:06
> I tried to remove other extensions, and the price shows correctly when I removed SteamDB extension ,that could be a compatibility issue.

That's the first time I've heard of such a compatibility issue with SteamDB, and I can't seem to reproduce it either 🤔
We determine your store country from the page script (auto-detected by Steam) or Steam's cookie, so you'll have to check if any other extension modifies those.

> But the lowest price still can not show correctly with a bundle, the problem still exists

That's because it's a dynamic bundle, and you already own parts of it. ITAD doesn't record the price history for all possible combinations, only the full bundle.

**Comment by candela97** [comment] 2022-07-17 09:10
I can't reproduce this with SteamDB enabled, and price history for bundles is working as intended. Closing for now, but feel free to follow up with more details.

**Closed by candela97** 2022-07-17 09:10 UTC
Labels: bug
