### ISSUE TITLE
[BUG] Crashes on game pages if install steam button is "replace with view in client"

### ISSUE THREAD

**Issue by zerodogg** [IsThereAnyDeal/AugmentedSteam#1693] opened 2023-07-08 14:52 UTC
If the "install steam button" setting is "replace with view in client" then I get `TypeError: e is null[AugmentedSteam.js:162:12](webpack://augmented-steam/src/js/Content/Modules/AugmentedSteam.js)`. The lines correspond to

```js
    static _handleInstallSteamButton() {
        const option = SyncedStorage.get("installsteam");
        if (option === "hide") {
            document.querySelector("div.header_installsteam_btn")?.remove();
        } else if (option === "replace") {
            const btn = document.querySelector("div.header_installsteam_btn > a");
            btn.textContent = Localization.str.viewinclient;
            btn.href = `steam://openurl/${window.location.href}`;
            btn.classList.add("es_steamclient_btn");
        }
    }
```

And the offending line is `btn.textContent = Localization.str.viewinclient;`. Locale for the browser is Norwegian Nynorsk.

Switching over to "hide" fixes it.

### Specifications

  - Augmented Steam Version: 2.4.1
  - Browser Version: Firefox 115.0

**Comment by candela97** [comment] 2023-07-08 16:50
Duplicate of #1654. The new version has been submitted and is pending review on AMO.

**Closed by candela97** 2023-07-08 16:50 UTC
Labels: bug
