### ISSUE TITLE
[BUG] Interfering with steam market auto agree scripts and extensions

### ISSUE THREAD

**Issue by pacopepepipo** [IsThereAnyDeal/AugmentedSteam#1038] opened 2021-02-02 21:34 UTC
### Expected Behavior
To not interfere with other 

### Actual Behavior
When AS is enabled, the other extensions to check the box of I agree on the market automatically, don't work

### Steps to Reproduce the Problem

  1. Enable AS
  2. Install https://chrome.google.com/webstore/detail/steam-market-auto-agree/hdommeagcldeibnepgadkfbhiofkndgf?hl=en
  3. wont work

### Specifications

  - Augmented Steam Version: latest
  - Browser Version : chrome latest

**Comment by candela97** [comment] 2021-02-05 15:39
There may very well be conflicts if 2 extensions try to manipulate the state of the same checkbox. Since you're here, I suggest you rely on Augmented Steam for this funtionality 😄.

**Comment by MxtOUT** [comment] 2021-02-06 12:37
wdym not work? It works for me

**Comment by Revadike** [comment] 2021-02-06 13:01
> wdym not work? It works for me

I think he wants you to add compatibility for other third party addons. I don't know if that's in your scope...

**Comment by pacopepepipo** [comment] 2021-02-07 11:12
> There may very well be conflicts if 2 extensions try to manipulate the state of the same checkbox. Since you're here, I suggest you rely on Augmented Steam for this funtionality 😄.

does it have it?

Maybe I'm blind, it's the first thing I looked on options but I didn't see it

**Comment by MxtOUT** [comment] 2021-02-10 15:30
What is "not working"?
The checkbox isn't checked?

**Comment by candela97** [comment] 2022-08-23 15:46
This feature is enabled by default without an option. Closing for now since we can't seem to reproduce this. Feel free to comment if there're still problems.

**Closed by candela97** 2022-08-23 15:46 UTC
Labels: bug, more info needed
