### ISSUE TITLE
[BUG]price compare settings not effect

### ISSUE THREAD

**Issue by ExcuseLme** [IsThereAnyDeal/AugmentedSteam#1949] opened 2024-06-28 11:12 UTC
### Expected Behavior
in price compare setting page, I just selected steam, wish it just show the lowest price in steam

### Actual Behavior
but it always show the lowest price from all game shop, include other game shop that I didn't selected

### Steps to Reproduce the Problem

  1. goto setting page
  2. goto "price" setting page
  3. turn the switcher "compare with all shop" off
  4. turn all child switchers off expect steam
  5. goto wishlist hover on any game, it will show the lowest price from other game shop if other shops price is lower than steam
  6. still happens in game information page

### Specifications

  - Augmented Steam Version: v3 ~ v4
  - Browser Version: chrome 120 ~ chrome 126

**Comment by ExcuseLme** [comment] 2024-06-28 11:13
I have tried to invalid cache and reinstall the extension, but not effect

**Comment by candela97** [comment] 2024-07-21 15:39
Duplicate of #1906

**Closed by candela97** 2024-07-21 15:39 UTC
Labels: bug, server
