### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by subZEROx265** [IsThereAnyDeal/AugmentedSteam#1770] opened 2023-09-15 08:45 UTC
### Expected Behavior
"Notes" button show on app pages and wish list

### Actual Behavior
"Notes" button missing from app pages and wish list

### Steps to Reproduce the Problem

  1. No reinstall or anything of Augmented Steam
  2. Just found out that notes are missingwhen try to make a note
  3. 

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Edge Version 116.0.1938.81 (Official build) (64-bit)

**Comment by candela97** [comment] 2023-09-15 09:31
Duplicate of #1748.

We've released v2.6 that fixes this.

**Closed by candela97** 2023-09-15 09:31 UTC
Labels: bug
