### ISSUE TITLE
[FEATURE REQUEST] Add filter for release date

### ISSUE THREAD

**Issue by MoTem** [IsThereAnyDeal/AugmentedSteam#1711] opened 2023-07-16 01:51 UTC
### Current Behavior (if any)
Steam search page doesn't give any option to filter out games based on a specific release year such as "only show games released after 2010". It only allows sorting by release date. 

### Desired Behavior
In the store search page, adding an extra filter similar to the "Reviews Count" addon where we can input the start and end release years, and the addon only shows games in that range. Inputting only the start year will mean - show all games released after that year. For only the end year, it will be vice versa - show all games released before this year. There is no need to add a filter for months in my opinion as just a simple release year range should be good enough. 

### Motivation / Use Case for Changing the Behavior
Sometimes you would want to only see old/new games.

**Comment by candela97** [comment] 2023-07-16 04:48
Duplicate of #1297. Filtering by year is probably the only thing we can do, since the abbreviated months are localized and will be too complicated to parse the whole date.

**Closed by candela97** 2023-07-16 04:48 UTC
Labels: augmentation
