### ISSUE TITLE
[FEATURE REQUEST] Make Price History Information use regional pricing

### ISSUE THREAD

**Issue by NutchapolSal** [IsThereAnyDeal/AugmentedSteam#1314] opened 2021-11-27 17:05 UTC
![image](https://user-images.githubusercontent.com/17706539/143690102-3cd72d6a-6b87-425d-93d8-5a6ec5978e48.png)

### Current Behavior (if any)
(see image) Price History Information uses USD prices converted to regional currency, which does not match the regional pricing

### Desired Behavior
(see image) Price History Information uses regional pricing

### Motivation / Use Case for Changing the Behavior
Current behavior is a bit confusing but may need complete rework to IsThereAnyDeal for this to work

**Comment by candela97** [comment] 2021-11-27 17:29
Yes that's because ITAD doesn't support the currency you're using, duplicate of #482.

**Closed** 2021-12-23 12:56 UTC
Labels: duplicate, augmentation
