### ISSUE TITLE
[FEATURE REQUEST] Remember search filters

### ISSUE THREAD

**Issue by Revadike** [IsThereAnyDeal/AugmentedSteam#1119] opened 2021-03-15 22:22 UTC
### Current Behavior (if any)
Not all steam store search filters are remembered. 

### Desired Behavior
Remember search filters, like app type. 

### Motivation / Use Case for Changing the Behavior
I hate how I always have to filter for type 'game' again after closing the tab.

**Comment by KamikiriTW** [comment] 2022-03-26 03:59
I need this too!
hate to see lot of DLC and Bundle appear in result.
or is anyway i can add some code to achieve this by my self?

**Comment by candela97** [comment] 2022-08-23 15:59
Duplicate of #808

**Closed by candela97** 2022-08-23 15:59 UTC
Labels: duplicate, augmentation
