### ISSUE TITLE
[BUG] "Install Steam" button doesn't hide

### ISSUE THREAD

**Issue by Duke-M-commits** [IsThereAnyDeal/AugmentedSteam#1704] opened 2023-07-11 12:42 UTC
### Expected Behavior
The "Install Steam" button should be hidden when configured 

### Actual Behavior
It doesn't hide.

### Steps to Reproduce the Problem

  1. Set `"Install Steam" button` to "Hide"
  2. Result: 
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/69652463/34ad6d8a-0ffc-42ce-9c17-83105ad485e0)

### Specifications

  - Augmented Steam Version: 2.4.1
  - Browser Version: Firefox 115.0.1

It's basically this bug again: #824

Additional info, regarding issue 824 discussion:
I never used SteamDB's extension and that augumented-steam-option hid the button in the header until recently.

**Comment by candela97** [comment] 2023-07-11 14:47
This is unrelated to that issue, instead a duplicate of https://github.com/IsThereAnyDeal/AugmentedSteam/issues/1654. The new version has been submitted and is pending review on AMO.

**Closed by candela97** 2023-07-11 14:47 UTC
Labels: bug

**Comment by Duke-M-commits** [comment] 2023-07-12 08:05
FYI: regarding 1654
The non-functionality of this feature does not block the rest of the features, in my case. This is why I referenced to 824.
