### ISSUE TITLE
[BUG] Stuck on "Augmented Steam loading data..."

### ISSUE THREAD

**Issue by Jademalo** [IsThereAnyDeal/AugmentedSteam#1671] opened 2023-06-29 23:09 UTC
### Expected Behavior
The addon to load and function

### Actual Behavior
The addon gets stuck on "Augmented Steam loading data...", and the functionality is never available

 ```
Augmented Steam v2.4.1  https://augmentedsteam.com/ [Page.js:88:16](webpack://augmented-steam/src/js/Content/Features/Page.js)
TypeError: e is null  [AugmentedSteam.js:162:12](webpack://augmented-steam/src/js/Content/Modules/AugmentedSteam.js)
```

### Steps to Reproduce the Problem

  1. Load any game page on steam
  2. 
### Specifications

  - Augmented Steam Version: 2.4.1
  - Browser Version: Firefox 114

Honestly no idea why it's doing this, nor am I sure when it started. 
Based on the error, it's something to do with the Install Steam button, but I have no idea why it would be happening.

**Comment by mrdude38** [comment] 2023-06-30 01:14
If you change the "Install Steam" button option to Show, the issue goes away

**Comment by candela97** [comment] 2023-06-30 05:29
Duplicate of #1654

**Closed by candela97** 2023-06-30 05:29 UTC
Labels: bug, duplicate
