### ISSUE TITLE
[BUG] Price History Information settings do not apply to historical low

### ISSUE THREAD

**Issue by BlepBlep** [IsThereAnyDeal/AugmentedSteam#1916] opened 2024-05-13 04:44 UTC
### Expected Behavior
When viewing historical low on games, it should ignore un-checked stores.

### Actual Behavior
When viewing historical low on games, it shows un-checked stores.

### Steps to Reproduce the Problem

  1. Open store page
  2. Check historical low price

### Specifications

  - Augmented Steam Version: 3.1.1
  - Browser Version: Firefox 125.0.3

**Comment by candela97** [comment] 2024-07-21 15:38
Duplicate of #1906

**Closed by candela97** 2024-07-21 15:38 UTC
Labels: bug, itad
