### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by clemmy2** [IsThereAnyDeal/AugmentedSteam#1749] opened 2023-09-13 09:21 UTC
### Expected Behavior
All augmented steam features to work, especially "Force video to mp4" and global price comparison

### Actual Behavior
When I log into my steam account, augmented steam does not work. Logging out solves the issues

### Steps to Reproduce the Problem

  1. Log into Steam Account - Pricing Globe icon disappears, attempting to right click save trailers defaults to .webm format
  2. Log out of Steam account - Globe re-appears, right click save defaults to .mp4
 

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Chrome - 117.0.5938.63 AND Brave Browser (version 1.57.64 Chromium 116.0.5845.188)

**Comment by Lofbergio** [comment] 2023-09-13 09:34
The issue is with the option "Replace account name with community name", just disable it for now.

**Comment by MxtOUT** [comment] 2023-09-13 09:37
Duplicate of #1748

**Closed by MxtOUT** 2023-09-13 09:37 UTC
Labels: bug
