### ISSUE TITLE
[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by Xadeas** [IsThereAnyDeal/AugmentedSteam#1883] opened 2024-03-28 05:23 UTC
### Current Behavior (if any)
In Turkey prices are shown as USD on the front page.

### Desired Behavior
Could you give us an option to change the price shown on the front page to our regional currency?

### Motivation / Use Case for Changing the Behavior
Convenience :)

**Comment by candela97** [comment] 2024-03-28 17:19
Duplicate of #1817

**Closed by candela97** 2024-03-28 17:19 UTC
Labels: augmentation
