### ISSUE TITLE
[BUG] Price History Information when hovering over wishlist items doesn't show

### ISSUE THREAD

**Issue by lashatatu** [IsThereAnyDeal/AugmentedSteam#2084] opened 2024-11-25 18:09 UTC
### Expected Behavior
When hovering over wishlist items IsThereAnyDeal was showing up week ago 

### Actual Behavior
When hovering over the wishlist it has a default behavior

### Steps to Reproduce the Problem

  1.  go to wishlist
  2.  hover over wishlist item
 

### Specifications

  - Augmented Steam Version: 4.1.2
  - Browser Version: Brave Browser Version 1.73.91,  Chrome Version 131.0.6778.86

**Comment by k3kin** [comment] 2024-11-27 19:07
same

**Comment by candela97** [comment] 2024-11-27 21:07
The underlying cause is the same as #2080, so marking as a duplicate of that umbrella issue. We're working on it!

**Closed by candela97** 2024-11-27 21:07 UTC
Labels: bug
