### ISSUE TITLE
[BUG] Steam blocks market prices for marketable items when checking through them with Quick Sell enable

### ISSUE THREAD

**Issue by oeoeuhoh** [IsThereAnyDeal/AugmentedSteam#1513] opened 2022-10-31 20:48 UTC
### Actual Behavior
Quick Sell/Instant Sell buttons disappear after clicking through the marketable items for a bit. Checked the Community Market page for one of the item, the prices for seller and buyer are vanish.

### Steps to Reproduce the Problem

  1. Click on through trading cards, keys, marketable items for 5 - 8 times
  2.  Quick Sell/Instant Sell buttons disappear along with the prices from the detail item page

### Specifications

  - Augmented Steam Version: 2.3.3

**Comment by candela97** [comment] 2022-11-01 10:40
This is likely Steam servers throwing 429 To Many Requests. We've been getting several reports of this lately, and I can somewhat reproduce this too. There isn't much we can do about it though, so you'll have to wait it out or use the sell dialog for the time being.

**Comment by candela97** [comment] 2022-11-02 14:38
After a bit of testing, adding the `country` parameter seems to help, no idea why and it doesn't do anything AFAICT. Hopefully this and better caching will improve the situation.

**Comment by docwhat** [comment] 2022-11-24 06:57
> After a bit of testing, adding the `country` parameter to the request made to `market/itemordershistogram` seems to help, no idea why and it doesn't change the response AFAICT. Hopefully this and better caching for duplicate items will improve the situation.

You mean [this line](https://github.com/IsThereAnyDeal/AugmentedSteam/blob/68965f33a346a33fb1a405f87d8072727e4862e6/src/js/Content/Features/Community/Inventory/FQuickSellOptions.js#L163)?

**Comment by candela97** [comment] 2022-11-24 13:18
Yes, that's what's changed. The fix will be the next version.

**Comment by docwhat** [comment] 2022-12-01 19:13
I can confirm that commit f5cdec2e works for me. 🥳

**Comment by candela97** [comment] 2022-12-26 13:33
Closing as fixed, for now. Please leave a comment if further 429 issues arise, as for other errors, we now print the error message instead of silently failing, so please file a new issue if using Steam's sell dialog works but this feature doesn't.

**Closed by candela97** 2022-12-26 13:33 UTC
Labels: bug
