### ISSUE TITLE
[BUG] Augmented Steam breaks when replacing "Install Steam" button with "View in Client"

### ISSUE THREAD

**Issue by ZachFett** [IsThereAnyDeal/AugmentedSteam#1669] opened 2023-06-27 16:19 UTC
### Expected Behavior
Augmented Steam loads properly.

### Actual Behavior
When setting the _"'Install Steam" button_ to _Replace with "View in Client"_, the top right loading bar gets stuck immediately and never finishes loading.

### Steps to Reproduce the Problem

  1. Go to Augmented Steam options
  2. Change _"Install Steam" button_ to _Replace with "View in Client"_
  3. Refresh any page on Steam

### Specifications

  - Augmented Steam Version: 2.4.1
  - Browser Version: Chrome 64-bit 114.0.5735.134

**Comment by candela97** [comment] 2023-06-27 16:27
Duplicate of #1654

**Closed by candela97** 2023-06-27 16:27 UTC
Labels: bug, duplicate
