### ISSUE TITLE
Achievement sorting doesnt work

### ISSUE THREAD

**Issue by GaleCro** [IsThereAnyDeal/AugmentedSteam#1342] opened 2021-12-25 13:15 UTC
I just want to address a lil bug on augmented steam extension, a feature for sorting achievements by date unlocked isnt working for some reason on my friends profiles, but on my profile it works pefectl
![Screenshot_9](https://user-images.githubusercontent.com/28599838/147385714-9a6730e5-35ea-4f69-9de6-dcacbe671ae0.png)
y

**Comment by candela97** [comment] 2021-12-26 02:12
Duplicate of #1193

**Closed** 2021-12-26 11:39 UTC
Labels: duplicate
