### ISSUE TITLE
Add "Price BELOW" search filter

### ISSUE THREAD

**Issue by RomanKornev** [IsThereAnyDeal/AugmentedSteam#810] opened 2020-03-17 13:03 UTC
Suggestion to add a price below filter, i.e. "Items that cost less than X" to filter out cheap games.
Literally the same thing as an existing filter but inverted.
See here:
https://github.com/tfedor/AugmentedSteam/blob/445e314d46c4e7aed5eff77d173d34decc100b2e/js/content/store.js#L2931-L2931

**Comment by candela97** [comment] 2022-08-23 17:48
Duplicate of #120

**Closed** 2022-08-23 17:48 UTC
Labels: duplicate, augmentation
