### ISSUE TITLE
[BUG] Calculate Total Size doesn't appear anymore?

### ISSUE THREAD

**Issue by spectywecty** [IsThereAnyDeal/AugmentedSteam#1764] opened 2023-09-14 05:24 UTC
### Expected Behavior
A button to calculate total addon size should be there on the subscribed addon page.

### Actual Behavior
The button isn't there anymore.

### Steps to Reproduce the Problem

  1. N/A (It just started happening to me starting from yesterday)

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Opera GX LVL 5 (core: 101.0.4843.85)

**Comment by MxtOUT** [comment] 2023-09-14 07:44
Duplicate of https://github.com/IsThereAnyDeal/AugmentedSteam/issues/1748.
Chrome / Opera should already have the fix available, please check for manual updates.

**Closed by MxtOUT** 2023-09-14 07:44 UTC
Labels: bug, duplicate
