### ISSUE TITLE
[BUG] Extension no longer loads correctly on Steamcommunity.com

### ISSUE THREAD

**Issue by daemond-dev** [IsThereAnyDeal/AugmentedSteam#1773] opened 2023-09-18 16:56 UTC
### Expected Behavior
Upon visiting any page on Steam Community, the extension loads correctly and adds the intended functionality to the browser.

### Actual Behavior
When visiting any page on Steam Community, including Market and Inventory, extension stalls out while loading and has completely stopped working. Loading icon remains stuck.

### Steps to Reproduce the Problem

  1. Install extension from Microsoft extension store.
  2. Visit https://steamcommunity.com/
  3. Note that extension does not load

### Specifications

  - Augmented Steam Version: Version 2.5.0
  - Browser Version: Microsoft Edge
Version 116.0.1938.81 (Official build) (64-bit)
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/109979474/9183da6b-17ea-4309-9730-7dea37875805)

**Comment by candela97** [comment] 2023-09-18 18:37
Duplicate of #1748. You can either wait for the update to go live on the Edge store, or download AS from the Chrome store instead.

**Closed by candela97** 2023-09-18 18:37 UTC
Labels: bug
