### ISSUE TITLE
[BUG] Conflict with SteamDB extension

### ISSUE THREAD

**Issue by sheppard-tr** [IsThereAnyDeal/AugmentedSteam#1733] opened 2023-09-05 05:45 UTC
### Expected Behavior

SteamDB and PCGamingWiki buttons should be visible properly. (The buttons come with SteamDB extension)

### Actual Behavior

SteamDB and PCGamingWiki buttons are not visible properly. 

### Screenshot with Augmented Steam extension enabled
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/84243819/d70c6432-27c0-4e1b-b9b9-af3e004a25d0)

### Screenshot with Augmented Steam extension disabled
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/84243819/995cbd5c-5ddf-4350-b209-6fa3b60e5dde)

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: 116.0.5845.141

**Comment by candela97** [comment] 2023-09-05 11:35
Duplicate of #1692

**Closed by candela97** 2023-09-05 11:35 UTC
Labels: bug
