### ISSUE TITLE
[BUG] Steam "add to cart" is broken while Augmented Steam is enabled

### ISSUE THREAD

**Issue by aviraldg** [IsThereAnyDeal/AugmentedSteam#1865] opened 2024-03-18 10:32 UTC
### Expected Behavior
Clicking "add to cart" on a game adds it to my Steam cart while Augmented Steam is enabled.

### Actual Behavior
The page reloads when "add to cart" is clicked, and nothing is added to the cart.

### Steps to Reproduce the Problem

  1. Go to a game page on Steam.
  2. Click "add to cart"

### Specifications

  - Augmented Steam Version: 3.0.0
  - Browser Version: Version 122.0.6261.129 (Official Build) (64-bit)

**Comment by Wingzzzzy** [comment] 2024-03-18 13:53
I have the same problem. Its after the new Steam Store update.

**Comment by candela97** [comment] 2024-03-18 14:23
Duplicate of #1851

**Closed by candela97** 2024-03-18 14:23 UTC
Labels: bug
