### ISSUE TITLE
[BUG] Stuck on loading data

### ISSUE THREAD

**Issue by Dantasstic** [IsThereAnyDeal/AugmentedSteam#1763] opened 2023-09-14 02:14 UTC
### Expected Behavior
The Augmented Steam Loading bar should load and turn green

### Actual Behavior
The loading bar never proceeds past a single blip

### Steps to Reproduce the Problem

1. Be logged in to your Steam account

![2023-09-13 - 2010-51](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/48727187/cee62f91-f36b-4b9c-acd2-bdc3fbffa6ee)

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Firefox 117.0.1

**Comment by flaviof15** [comment] 2023-09-14 03:19
Same problem here.
Chrome v.117.0.5938.63 64 bits
Augmented Steam 
V. 2.5.0

I noticed that the problem only occurs when I am logged into my Steam account. If I log out, Augmented Steam works normally again.

**Comment by Dantasstic** [comment] 2023-09-14 03:22
> I noticed that the problem only occurs when I am logged into my Steam account. If I log out, Augmented Steam works normally again.

Good catch, that is the case for me as well. I have added that to the bug description.

**Comment by JerwinModavi** [comment] 2023-09-14 03:55
All features (as far as I can tell) of Augmented Steam have stopped working for me while I'm logged into my Steam account. I tried uninstalling/reinstalling Augmented Steam, resetting Augmented Steam settings, and clearing all Google Chrome history (cookies, site settings, etc.), but it did not fix the issue.

Augmented Steam only appears to work for me when not logged into my Steam account.

**Comment by MxtOUT** [comment] 2023-09-14 07:43
Duplicate of #1748.
Chrome should already have the fix available, please check for manual updates.

**Closed by MxtOUT** 2023-09-14 07:43 UTC
Labels: bug, duplicate
