### ISSUE TITLE
[BUG] "Sort reviews by Helpful" is broken

### ISSUE THREAD

**Issue by BlueRaja** [IsThereAnyDeal/AugmentedSteam#1598] opened 2023-03-15 01:40 UTC
### Expected Behavior
Reviews are sorted by 'Helpful'

### Actual Behavior
The top- and bottom-halves of page 1 show two separate sets of random games (not the ones with the highest "helpful" ranking) that are each separately sorted by "Helpful". Then on page two, the top half shows another set of random games sorted by helpful.  On the bottom-half of page 2, the actual list of "most helpful" games finally starts.  It continues to work correctly from page-3 onward

### Steps to Reproduce the Problem

  1. Go to [my list of reviews](https://steamcommunity.com/id/BlueRaja/recommended/?p=1)
  2. Sort by "helpful". It may take a minute.

### Specifications

  - Augmented Steam Version: 2.4.1
  - Browser Version: Firefox 110.0.1, Windows 11

**Comment by candela97** [comment] 2023-03-15 08:23
Marking as a duplicate of #1526. Thanks for providing your profile to test with!

**Closed by candela97** 2023-03-15 08:23 UTC
Labels: bug, duplicate
