### ISSUE TITLE
[FEATURE REQUEST] Show game size on store pages

### ISSUE THREAD

**Issue by win7guru** [IsThereAnyDeal/AugmentedSteam#1800] opened 2023-11-20 05:10 UTC
### Current Behavior
> Currently there is no way to see the size of the app/game on its store page.

### Desired Behavior
> Since there are so many modifications with Augmented Steam, could you please find a way to show a game's size (sort of like SteamDB with depots) at the top of the game page, perhaps the same place that shows the Developer website (also augmented) or as a small banner.

### Motivation / Use Case for Changing the Behavior
> I would like to see this, because I have little storage and when I go on a Demo downloading spree, I need to keep track of how large the app size is, so my laptop doesn't start running out of storage.  I propose that this be added if it is possible to do so and I feel that others will benefit from this augmentation.

**Comment by nc7s** [comment] 2023-11-26 20:40
<img width="649" alt="image" src="https://github.com/IsThereAnyDeal/AugmentedSteam/assets/4474501/716d35c7-abe1-497e-93c2-420d617aeda9">

**Comment by candela97** [comment] 2023-12-09 18:16
Duplicate of #134. SteamDB is in a better position to provide this info, but as noted it is not accurate (dowload size does not equal disk size), and unfortunately there's no easy way to get the disk size for a specific depot at the moment.

**Closed by candela97** 2023-12-09 18:16 UTC
Labels: duplicate, augmentation
