### ISSUE TITLE
Large wishlist always broken if this extension enabled on Chrome

### ISSUE THREAD

**Issue by kokizzu** [IsThereAnyDeal/AugmentedSteam#745] opened 2020-01-18 03:41 UTC
It causes most ajax request to show code 500 errors like this:

https://store.steampowered.com/wishlist/profiles/76561198089745840/wishlistdata/?p=2
https://store.steampowered.com/wishlist/profiles/76561198089745840/wishlistdata/?p=4
https://store.steampowered.com/wishlist/profiles/76561198089745840/wishlistdata/?p=7
https://store.steampowered.com/wishlist/profiles/76561198089745840/wishlistdata/?p=9

https://youtu.be/XBCoicQAPH0

**Comment by MxtOUT** [comment] 2020-01-19 16:57
I see that you're using Enhanced Steam, which is outdated.
The continuation of ES is Augmented Steam, which you can download for [Firefox ](https://addons.mozilla.org/en-US/firefox/addon/enhanced-steam-an-itad-fork/)and [Chrome](https://chrome.google.com/webstore/detail/augmented-steam/dnhpnfgdlenaccegplpojghhmaamnnfp?hl=en)

**Comment by kokizzu** [comment] 2020-01-19 17:56
yes, the error 500 only happened if i enable any of enchanced steam, augmented steam, or steamdb extension..

**Comment by MxtOUT** [comment] 2020-01-19 18:03
I don't see that you have Augmented Steam installed

**Comment by kokizzu** [comment] 2020-01-19 18:19
yes, that video only shows enhanced steam, but i tried also with augmented steam and steamdb extension each

**Comment by MxtOUT** [comment] 2020-01-19 18:28
I doubt that this has something to do with these extensions since they're not modifying the behavior of the wishlist loading.
Have you tried clearing cache / cookies?

**Comment by Revadike** [comment] 2020-01-20 00:47
I also have this sometimes. I didn't know it was caused by AS. But it doesn't happen all the time and seems to be happening less nowadays.

**Comment by kokizzu** [comment] 2020-01-20 00:55
yes @MxtOUT  i used ctrl+shift+R to hard reload (ignore cache) while javascript console/chrome dev tools is opened

**Comment by MxtOUT** [comment] 2023-09-12 07:51
Since there haven't been recent reports or confirmations of this issue and a lot of things have changed on our and on Steam's side since the original report, I am going to close this issue for now and see it as solved.
If it still persists, please comment and / or reopen this issue.

**Closed by MxtOUT** 2023-09-12 07:51 UTC
Labels: bug, help wanted
