### ISSUE TITLE
[BUG] Augmented Steam applies coupons when they cannot be

### ISSUE THREAD

**Issue by Tyler799** [IsThereAnyDeal/AugmentedSteam#1824] opened 2024-01-19 00:03 UTC
### Expected Behavior

Augmented Steam should ignore coupons from GreenManGaming like today's, 'JAN18' when they are less than the current discount price, rather than applying the two additively. So if the current game is say, 28% off, and JAN18 offers (I think) 13% off, Augmented Steam should show a price reflecting the larger 28% discount, not a combined 41% discount.

### Actual Behavior

Augmented Steam combined GMG discounts when GMG does not allow this - only the larger will ever be used.

### Steps to Reproduce the Problem

  1.  Go to GMG's store page for the product: https://www.greenmangaming.com/games/turnip-boy-robs-a-bank-pc/
  2. Put the item in the cart and go to checkout
  3. Try to apply the code Augmented Steam suggested (in this case, JAN18). Notice that it will not let you.

### Specifications

  - Augmented Steam Version: Latest plugin version on Firefox
  - Browser Version: 121.0.1 (64-bit)
  
  Please note that this has been broken for as long as Augmented Steam has been around, and I'm fairly certain this goes back to when it was Enhanced Steam. I hope some day this is fixed.

**Comment by candela97** [comment] 2024-01-23 15:43
Duplicate of #1489

**Closed by candela97** 2024-01-23 15:43 UTC
Labels: bug, duplicate
