### ISSUE TITLE
[FEATURE REQUEST] Displaying the game you already have on your account

### ISSUE THREAD

**Issue by SeregaMihalkin** [IsThereAnyDeal/AugmentedSteam#1726] opened 2023-08-13 06:12 UTC
### Current Behavior (if any)
Nothing happens

### Desired Behavior
display the name of the game you have, like in the SteamDB extension

### Motivation / Use Case for Changing the Behavior
comfortable
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/40563573/5bdf45ff-6f20-443f-ac87-c5a4fe50f5b3)

**Comment by SeregaMihalkin** [comment] 2023-08-13 06:13
I may not have noticed such a function in the settings, if so, please show it on the screen.

**Comment by candela97** [comment] 2023-08-25 15:28
Duplicate of #1058 and ultimately #449.

**Closed by candela97** 2023-08-25 15:28 UTC
Labels: augmentation
