### ISSUE TITLE
[FEATURE REQUEST] Notes manager

### ISSUE THREAD

**Issue by pakoito** [IsThereAnyDeal/AugmentedSteam#1805] opened 2023-12-08 01:00 UTC
### Current Behavior (if any)
My notes are at near capacity and I know I have some I'd like to delete from games I've already purchased.

### Desired Behavior
I'd like to review all my notes in a single place and clear only some of them of my choice.

### Motivation / Use Case for Changing the Behavior
Clear storage so I can continue adding more synchronized notes.

**Comment by candela97** [comment] 2023-12-09 19:09
Duplicate of #429. It's being worked on for sure!

**Closed by candela97** 2023-12-09 19:09 UTC
Labels: duplicate, augmentation
