### ISSUE TITLE
[BUG] Augmented Steam is entirely broken since the Steam UI update a few weeks ago

### ISSUE THREAD

**Issue by kazerniel** [IsThereAnyDeal/AugmentedSteam#1687] opened 2023-07-06 20:22 UTC
### Expected Behavior
To continue working as it always has - show third party site links on app pages, show instant sell in inventory, show Card Exchange button on badge pages, turn community hub links into store links in the activity feed, etc.

### Actual Behavior
Nothing happens, the app just permanently stays with the green dot on the left, "Augmented Steam loading data..."

I tried emptying the cache many times, even tried reinstalling the extension, neither made a difference.

### Specifications

  - Augmented Steam Version: 2.4.1
  - Browser Version: Firefox 114.0.2

**Comment by candela97** [comment] 2023-07-06 22:35
Duplicate of #1654. Please refer to that issue for a solution until the next version lands.

**Closed by candela97** 2023-07-06 22:35 UTC
Labels: bug

**Comment by kazerniel** [comment] 2023-07-07 10:24
Ahh thanks, didn't realise from the title that it's the same issue 😅
