### ISSUE TITLE
[BUG] Prices showing over game title / image

### ISSUE THREAD

**Issue by blxrr** [IsThereAnyDeal/AugmentedSteam#1886] opened 2024-03-30 07:24 UTC
### Expected Behavior
Should show the prices of the games underneath the game information

### Actual Behavior
Shows it over the game title/cover image instead

<img width="571" alt="91708ac08a3b9aa14cd49a3ca53273c2" src="https://github.com/IsThereAnyDeal/AugmentedSteam/assets/12877061/f8744651-8bb4-4989-803a-9ba446439f33">

### Steps to Reproduce the Problem

  1. Go to Steam wishlist
  2. Hover over game

### Specifications

  - Augmented Steam Version: 3.1.0
  - Browser Version: Firefox 124.0.1 (64bit)

**Comment by candela97** [comment] 2024-03-30 15:53
Duplicate of #1871

**Closed by candela97** 2024-03-30 15:53 UTC
Labels: bug
