### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by hamburgercrisis** [IsThereAnyDeal/AugmentedSteam#1750] opened 2023-09-13 16:53 UTC
### Expected Behavior
Having the quick sell/instant sell buttons visible

### Actual Behavior
Not showing up
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/63331329/34df6529-6f26-4a79-b6fc-44abb35a9e74)
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/63331329/183ed73f-f415-4916-b9d8-93da40ba6e23)
Heres the console output
![image](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/63331329/53aaadcc-80d9-4969-a876-2e40ce5428ec)
Heres my settings

### Specifications

  - Augmented Steam Version: 2.5.0
  - Browser Version: Chrome Version 117.0.5938.63 (Official Build) (64-bit)

**Comment by MxtOUT** [comment] 2023-09-13 16:58
Duplicate of #1748

**Closed by MxtOUT** 2023-09-13 16:58 UTC
Labels: bug
