### ISSUE TITLE
[BUG] Scrolling up large wishlists from the bottom results in an unresponsive page for above a minute

### ISSUE THREAD

**Issue by gab** [IsThereAnyDeal/AugmentedSteam#1115] opened 2021-03-13 02:45 UTC
### Expected Behavior
I can scroll up and down the page and wishlist items load in as needed, like in vanilla Steam behavior (tested).

I don't have to wait a minute to see a given section of the wishlist after scrolling around a bit.

### Actual Behavior
If I scroll all the way down the page, then start scrolling up, pretty quickly items stop loading in. If I keep scrolling up to the top, when I reach it everything is blank, even the "header" page elements. At this point scrolling down doesn't display anything either except a small section of the wishlist, everything else is gone. Curiously Ctrl+refresh doesn't even necessarily fix it, I've had to close the tab and open a new wishlist one to see my wishlist again.

At first I thought it was completely broken, but I've now realized that if I wait long enough (more than a minute) the wishlist will have loaded all elements and start showing them again as you scroll.

### Steps to Reproduce the Problem

  1. Have 1015 games in your Steam wishlist
  2. Scroll down to the bottom of the page relatively quickly, using the scrollbar handle. Observe that the last elements of the wishlist don't show (for me the last element displayed is often rank 945 out of 1015).
  3. Scroll up to the top of the page - observe that wishlist elements now have stopped loading dynamically.
  4. Upon reaching the top, observe that the page is now completely blank, no matter in which direction you attempt to scroll, except for the small incomplete section at the bottom of the wishlist which is still loaded.
  5. Wait 1-3 minutes. Eventually all items in the wishlist will have been loaded, they'll appear, and the scrolling displays the correct items again.

### Specifications

  - Augmented Steam Version: 2.0.1
  - Browser Version : Chrome 89.0.4389.82 64-bit

**Comment by candela97** [comment] 2021-03-14 14:42
An easier way to trigger this is to move the scrollbar around very fast and stop at random intervals.

Something to do with the refactor to `TimeUtils.resettableTimer()`? Doesn't seem to happen with the older `setTimout()`. @MxtOUT

**Comment by MxtOUT** [comment] 2021-04-06 18:13
I can't reproduce this and I also can't find a reason in the `ResettableTimer` class for why it should excessively use resources

**Comment by CUD** [comment] 2021-09-22 02:15
I was looking for a possible fix for this same issue.
My wishlist admittedly very large at over 3000 items but it was occurring when I was 2000+ and as reported here for gab at 1000+.

I was hoping to disable the extension for the wishlist page entirely to prevent this but can't seem to find a way to do so. The two wishlist options in AS options are unchecked currently.

**Comment by DoLLo73** [comment] 2021-10-31 07:09
Same problem(large wishlist and chrome lagging badly and not load correctly)here. No problem at all with Firefox.

**Closed** 2023-05-17 11:32 UTC
Labels: bug, help wanted
