### ISSUE TITLE
[FEATURE REQUEST] Realistic Historical Low Prices

### ISSUE THREAD

**Issue by Dilbao** [IsThereAnyDeal/AugmentedSteam#1792] opened 2023-11-12 14:56 UTC
Currently the "Historical low" prices show the lowest possible price in history, as you would expect.

However, if the game was given away for a short period of time, the lowest price is shown as "0". If you missed this opportunity, the game may never be distributed for free again. It is not currently possible to see the realistic lowest price of the games.

I think that prices with "0" should be ignored in calculation when showing lowest prices, so it will be easier to understand whether the current prices are a deal or not.

**Comment by candela97** [comment] 2023-11-12 16:42
Duplicate of #1232

**Closed by candela97** 2023-11-12 16:42 UTC
Labels: augmentation
