### ISSUE TITLE
Current best price in wishlist overlapping game title [BUG]

### ISSUE THREAD

**Issue by J-Aurica** [IsThereAnyDeal/AugmentedSteam#1900] opened 2024-04-13 01:13 UTC
### Expected Behavior
Best price pops down when cursor is over a game title in wishlist

### Actual Behavior
Best price overlaps the game's title and is impossible to read

### Steps to Reproduce the Problem

  1. Go to wishlist
  2. Sort by your rank
  3. Place cursor over any game's title

### Specifications

  - Augmented Steam Version: 3.1.0  
  - Browser Version: Firefox 124.0.2 (64-bit)

![Capture](https://github.com/IsThereAnyDeal/AugmentedSteam/assets/113230180/5ded5279-8f18-41e3-96a3-3480f8aa8f65)

**Comment by candela97** [comment] 2024-04-13 15:39
Duplicate of #1871.
This will be fixed in 3.1.1 once it clears store reviews.

**Closed by candela97** 2024-04-13 15:39 UTC
Labels: bug
