### ISSUE TITLE
[BUG] "Prevent redirection when adding items to your Cart" breaks 100% discount purchase

### ISSUE THREAD

**Issue by metapone** [IsThereAnyDeal/AugmentedSteam#1569] opened 2023-01-07 10:10 UTC
### Expected Behavior

1. Navigate to one page with 100% discount promo, for example https://store.steampowered.com/app/2251260/Minion_Masters__Furry_Fury/
2. Click "Add to Account"
3. Page refresh, account displayed as already owned the item.

### Actual Behavior
1. Navigate to one page with 100% discount promo, for example https://store.steampowered.com/app/2251260/Minion_Masters__Furry_Fury/
2. Click "Add to Account"
3. The item is added to cart, which even if I try to check out with the cart an error will be displayed instead.

### Specifications

  - Augmented Steam Version: 2.4.0
  - Browser Version: Firefox 108.0.2 (64-bit)

**Comment by alpasy** [comment] 2023-01-07 17:30
Came here to report the same bug. Had to (guess what's causing it and) disable the option to get the free DLC.

**Comment by candela97** [comment] 2023-01-08 13:04
Duplicate of #1546

**Closed by candela97** 2023-01-08 13:04 UTC
Labels: bug
