### ISSUE TITLE
[BUG] The "Tag" / "Items you own" setting state does not affect the display of games in search results on the Steam Search

### ISSUE THREAD

**Issue by Korb** [IsThereAnyDeal/AugmentedSteam#1333] opened 2021-12-19 11:01 UTC
### Expected Behavior
By checking the "Tag" / "Items you own" checkbox in the add-on settings, I expect that next to each purchased game in the Steam search results list will be displayed the corresponding mark of the color selected in the add-on settings.

### Actual Behavior
The purchased game page displays `Age of Wonders: Planetfall is already in your Steam library`, but it does not stand out from other games in the search results.

### Steps to Reproduce the Problem

  1. Go to [Steam Search page](https://store.steampowered.com/search/)
  2. Enter the text `Planetfall`, press the Enter

### Specifications

  - Augmented Steam Version: 2.2.1 (7 November 2021)
  - Mozilla Firefox 96.0b6 (64-bit), Microsoft Windows 10.0.19043.1415

![Screenshot 2021-12-19 at 13-59-30 Steam Search](https://user-images.githubusercontent.com/3509797/146672559-cbc370bc-d274-4784-b8a8-e9969bb0b37f.png)
![Screenshot 2021-12-19 at 14-00-02 Age of Wonders Planetfall on Steam](https://user-images.githubusercontent.com/3509797/146672560-cc757e67-b0c0-4e0d-82a6-53cdbef7c65d.png)
![2021-12-19_14-01-23](https://user-images.githubusercontent.com/3509797/146672585-4873edda-b665-4335-832c-88b90395ea44.png)

**Comment by MxtOUT** [comment] 2021-12-23 12:30
Duplicate of #1310, fixed by #1312

**Closed by MxtOUT** 2021-12-23 12:30 UTC
Labels: bug
